In [1]:
import pandas as pd

In [3]:
data = pd.read_csv('./Data/서울시 학교 기본정보.csv', encoding='euc-kr')

In [6]:
data['학교종류명'].unique()

array(['각종학교(중)', '초등학교', '중학교', '외국인학교', '각종학교(고)', '평생학교(초)-3년6학기',
       '각종학교(초)', '방송통신중학교', '고등학교', '특수학교', '평생학교(고)-2년6학기',
       '평생학교(고)-3년6학기', '평생학교(중)-2년6학기', '평생학교(중)-3년6학기', '고등기술학교',
       '방송통신고등학교', '공동실습소'], dtype=object)

In [15]:
school = data[(data['학교종류명'] == '초등학교') | (data['학교종류명'] == '중학교') | (data['학교종류명'] == '고등학교')]
school.head()

,학교종류명,설립구분,표준학교코드,학교명,영문학교명,관할조직명,도로명우편번호,도로명주소,도로명상세주소,전화번호,...,주야구분명,설립일자,개교기념일,시도교육청코드,시도교육청명,소재지명,주야과정,계열명,학과명,적재일시
1,초등학교,공립,7134150,서울숭신초등학교,Seoul Soongshin Elementary School,서울특별시성동광진교육지원청,4702,서울특별시 성동구 마장로 161,(하왕십리동),02-2252-5950,...,주간,19590403,19590403,B10,서울특별시교육청,서울특별시,NaN,NaN,NaN,20230421
2,중학교,공립,7134142,행당중학교,Haengdang Middle School,서울특별시성동광진교육지원청,4764,서울특별시 성동구 왕십리로 189,(행당동/행당중학교),02-2292-2721,...,주간,19680806,19681002,B10,서울특별시교육청,서울특별시,NaN,NaN,NaN,20230421
3,중학교,사립,7134141,한양대학교사범대학부속중학교,Hanyang University Middle School,서울특별시성동광진교육지원청,4761,서울특별시 성동구 마조로 42,(사근동/한양사대부속중?고등학교),02-2200-3700,...,주간,19600118,19600118,B10,서울특별시교육청,서울특별시,NaN,NaN,NaN,20230421
4,중학교,공립,7134140,자양중학교,Jayang Middle School,서울특별시성동광진교육지원청,5069,서울특별시 광진구 뚝섬로41길 33,(자양동/서울자양중학교),02-446-0365,...,주간,19840301,19840301,B10,서울특별시교육청,서울특별시,NaN,NaN,NaN,20230421
5,중학교,공립,7134139,용곡중학교,Yong-gok Middle School,서울특별시성동광진교육지원청,4940,서울특별시 광진구 용마산로22길 76,(중곡동/용곡중학교),02-452-2622,...,주간,19821209,19830504,B10,서울특별시교육청,서울특별시,NaN,NaN,NaN,20230421

In [16]:
school.shape

(3502, 28)

In [17]:
established = school['설립일자']

In [22]:
established_year = [str(i)[:4] for i in established]

In [23]:
established_year

['1959',
 '1968',
 '1960',
 '1984',
 '1982',
 '1984',
 '2005',
 '1984',
 '1968',
 '1967',
 '1968',
 '2005',
 '1977',
 '1984',
 '1930',
 '1984',
 '1937',
 '1979',
 '1982',
 '1986',
 '1993',
 '2003',
 '1980',
 '1967',
 '1966',
 '1962',
 '1966',
 '2005',
 '1962',
 '1982',
 '1998',
 '1955',
 '1945',
 '2002',
 '1972',
 '1983',
 '1978',
 '1971',
 '1967',
 '2005',
 '1983',
 '1982',
 '1979',
 '2009',
 '1984',
 '1972',
 '1967',
 '1915',
 '2005',
 '2010',
 '1984',
 '1987',
 '1944',
 '1958',
 '1962',
 '1968',
 '1981',
 '1998',
 '2003',
 '1946',
 '1990',
 '1984',
 '1982',
 '1913',
 '1965',
 '1934',
 '1985',
 '1971',
 '1906',
 '1973',
 '1984',
 '1903',
 '1981',
 '1938',
 '1926',
 '1968',
 '1968',
 '1970',
 '1984',
 '1969',
 '1988',
 '1984',
 '1981',
 '1984',
 '1951',
 '1972',
 '1982',
 '1982',
 '1964',
 '1971',
 '1984',
 '1986',
 '2004',
 '1951',
 '1981',
 '1968',
 '1959',
 '1964',
 '1968',
 '1992',
 '1985',
 '2005',
 '1979',
 '1958',
 '1908',
 '2002',
 '1972',
 '1962',
 '1967',
 '1977',
 '1982',
 '1981',
 '1981',
 '1970',
 '1975',
 '1964',
 '2012',
 '1966',
 '2007',
 '1972',
 '1972',
 '2003',
 '1967',
 '1948',
 '2005',
 '1980',
 '1946',
 '1982',
 '1973',
 '1974',
 '1948',
 '1967',
 '1979',
 '1985',
 '1981',
 '1976',
 '1971',
 '1977',
 '1971',
 '1945',
 '1979',
 '2022',
 '2022',
 '2021',
 '2021',
 '2020',
 '2019',
 '2019',
 '2017',
 '2016',
 '1933',
 '1990',
 '1991',
 '1982',
 '1969',
 '1994',
 '1887',
 '1980',
 '1984',
 '1974',
 '1984',
 '1988',
 '1986',
 '1967',
 '1986',
 '1975',
 '1981',
 '1993',
 '1978',
 '2014',
 '1991',
 '1976',
 '1984',
 '1982',
 '1971',
 '1908',
 '1906',
 '1885',
 '1949',
 '1985',
 '1991',
 '2009',
 '1990',
 '1984',
 '1986',
 '1950',
 '1953',
 '1984',
 '1997',
 '1982',
 '2012',
 '2010',
 '1988',
 '1986',
 '1990',
 '1991',
 '1980',
 '1992',
 '1984',
 '1944',
 '1985',
 '1982',
 '1924',
 '2008',
 '1981',
 '1976',
 '1975',
 '1981',
 '1980',
 '1981',
 '1988',
 '1993',
 '1982',
 '1986',
 '1959',
 '1980',
 '1982',
 '1988',
 '1985',
 '1978',
 '2014',
 '1988',
 '1983',
 '1969',
 '2001',
 '1985',
 '1989',
 '1921',
 '1983',
 '2007',
 '1981',
 '1991',
 '2007',
 '1984',
 '1993',
 '1985',
 '1980',
 '1986',
 '1984',
 '1978',
 '1979',
 '1986',
 '1983',
 '1973',
 '1983',
 '1980',
 '1983',
 '1997',
 '1967',
 '2007',
 '1993',
 '2011',
 '1976',
 '1986',
 '1996',
 '1988',
 '1981',
 '1990',
 '2009',
 '1946',
 '2011',
 '1969',
 '1954',
 '1945',
 '1972',
 '1966',
 '1960',
 '1936',
 '1956',
 '1942',
 '1934',
 '1955',
 '1968',
 '2012',
 '1970',
 '1980',
 '1984',
 '1986',
 '1986',
 '1946',
 '1972',
 '2000',
 '1982',
 '1960',
 '2003',
 '1984',
 '1992',
 '2006',
 '1980',
 '1965',
 '1965',
 '1965',
 '1963',
 '1965',
 '1965',
 '1967',
 '1967',
 '1986',
 '1985',
 '1946',
 '1946',
 '2006',
 '1978',
 '2000',
 '1982',
 '1974',
 '1971',
 '1949',
 '1991',
 '1956',
 '1937',
 '1945',
 '1945',
 '1972',
 '1967',
 '2001',
 '1966',
 '1983',
 '1946',
 '1971',
 '2005',
 '1959',
 '1949',
 '2001',
 '1991',
 '1971',
 '1962',
 '1948',
 '1944',
 '1984',
 '2006',
 '2002',
 '2018',
 '2014',
 '2014',
 '2012',
 '2013',
 '2012',
 '1906',
 '1976',
 '1906',
 '1955',
 '1906',
 '1978',
 '1978',
 '1908',
 '1941',
 '1984',
 '1982',
 '1982',
 '1969',
 '1984',
 '1980',
 '1982',
 '1988',
 '1983',
 '1984',
 '1984',
 '1990',
 '1988',
 '1993',
 '1979',
 '1986',
 '1982',
 '1986',
 '1980',
 '1974',
 '1991',
 '1986',
 '1987',
 '1994',
 '1990',
 '1988',
 '1981',
 '1982',
 '1984',
 '2012',
 '1979',
 '1990',
 '1980',
 '1978',
 '1984',
 '1977',
 '1979',
 '1989',
 '1994',
 '1963',
 '1946',
 '1978',
 '1927',
 '1945',
 '1934',
 '1988',
 '1983',
 '1976',
 '1936',
 '1946',
 '1981',
 '1992',
 '1980',
 '1986',
 '1983',
 '1984',
 '1983',
 '1985',
 '1982',
 '1990',
 '1984',
 '1975',
 '1974',
 '1981',
 '2008',
 '1981',
 '1974',
 '1984',
 '1984',
 '1993',
 '1992',
 '1932',
 '1994',
 '1979',
 '1981',
 '1972',
 '1983',
 '1983',
 '1987',
 '1982',
 '1882',
 '1953',
 '2020',
 '1974',
 '1938',
 '1905',
 '1978',
 '1951',
 '1977',
 '1950',
 '1981',
 '1978',
 '2015',
 '1995',
 '1991',
 '1984',
 '2005',
 '1990',
 '1990',
 '1984',
 '1986',
 '1969',
 '1980',
 '1986',
 '1982',
 '1986',
 '1984',
 '2008',
 '1991',
 '1995',
 '1994',
 '1982',
 '1986',
 '1993',
 '1986',
 '2009',
 '1981',
 '1995',
 '1995',
 '1981',
 '1955',
 '1950',
 '1988',
 '1965',
 '2011',
 '2005',
 '1967',
 '1993',
 '1994',
 '2002',
 '1981',
 '1992',
 '2005',
 '1996',
 '1985',
 '1981',
 '1983',
 '1986',
 '1963',
 '1997',
 '2005',
 '1978',
 '1900',
 '1990',
 '1980',
 '1982',
 '1972',
 '1987',
 '1949',
 '1975',
 '1981',
 '1987',
 '1982',
 '1983',
 '2000',
 '1983',
 '1983',
 '2008',
 '1990',
 '1936',
 '1987',
 '1994',
 '1984',
 '1986',
 '1979',
 '1995',
 '2009',
 '1973',
 '1995',
 '1982',
 '1994',
 '1994',
 '1984',
 '1995',
 '2006',
 '1983',
 '1991',
 '1982',
 '1992',
 '1979',
 '1986',
 '1956',
 '1988',
 '1985',
 '1980',
 '1987',
 '1992',
 '1992',
 '1969',
 '1895',
 '1947',
 '1948',
 '1972',
 '1952',
 '1945',
 '1908',
 '1947',
 '1968',
 '1945',
 '1968',
 '1907',
 '1946',
 '1957',
 '1899',
 '1966',
 '1907',
 '1898',
 '1955',
 '1907',
 '1910',
 '1920',
 '1938',
 '1956',
 '1968',
 '1885',
 '1986',
 '1964',
 '1966',
 '1946',
 '1967',
 '1895',
 '1910',
 '1921',
 '1959',
 '1957',
 '1943',
 '1923',
 '1937',
 '1916',
 '1895',
 '1953',
 '1943',
 '1983',
 '1965',
 '1945',
 '1968',
 '2007',
 '1948',
 '1945',
 '1945',
 '1895',
 '1962',
 '1971',
 '1895',
 '1957',
 '1912',
 '1945',
 '1945',
 '1915',
 '1894',
 '1895',
 '1966',
 '1965',
 '1966',
 '2006',
 '1991',
 '1982',
 '2001',
 '1955',
 '1991',
 '1986',
 '1983',
 '1990',
 '1991',
 '1994',
 '1971',
 '1971',
 '2004',
 '1981',
 '1991',
 '1965',
 '1984',
 '1988',
 '1994',
 '1968',
 '2002',
 '1979',
 '1993',
 '1937',
 '1986',
 '1971',
 '1988',
 '1992',
 '1984',
 '1992',
 '1982',
 '1971',
 '1995',
 '1995',
 '1988',
 '1988',
 '1964',
 '1984',
 '1967',
 '1969',
 '1949',
 '1965',
 '1983',
 '1986',
 '2001',
 '1993',
 '1895',
 '1990',
 '1990',
 '1997',
 '1930',
 '1982',
 '1989',
 '1989',
 '1988',
 '1990',
 '1975',
 '1997',
 '1994',
 '1988',
 '1992',
 '1991',
 '1995',
 '1991',
 '1988',
 '2000',
 '1945',
 '1998',
 '1974',
 '1984',
 '1988',
 '1971',
 '1970',
 '1986',
 '1981',
 '1981',
 '2000',
 '1983',
 '1974',
 '1989',
 '1990',
 '1989',
 '1988',
 '1988',
 '1946',
 '1989',
 '1993',
 '1980',
 '1982',
 '1988',
 '1966',
 '2003',
 '1988',
 '1993',
 '1995',
 '1994',
 '1972',
 '1982',
 '1979',
 '1983',
 '2003',
 '1964',
 '1964',
 '2019',
 '2019',
 '2021',
 '2020',
 '2017',
 '2016',
 '2013',
 '2011',
 '1971',
 '1981',
 '1974',
 '1976',
 '1988',
 '1950',
 '1980',
 '1979',
 '1980',
 '1972',
 '1980',
 '1991',
 '1984',
 '1991',
 '1968',
 '1985',
 '1967',
 '1990',
 '1986',
 '1968',
 '1988',
 '1984',
 '1968',
 '1982',
 '1980',
 '1990',
 '1978',
 '1984',
 '1969',
 '1987',
 '1984',
 '1970',
 '1967',
 '1982',
 '1979',
 '1915',
 '1984',
 '1986',
 '1943',
 '1982',
 '1949',
 '1967',
 '2002',
 '1967',
 '1979',
 '2005',
 '1982',
 '1945',
 '1956',
 '1956',
 '1971',
 '1991',
 '1991',
 '1982',
 '2002',
 '1982',
 '1995',
 '1982',
 '1911',
 '1972',
 '2007',
 '1973',
 '2002',
 '1955',
 '1981',
 '1985',
 '1993',
 '1985',
 '1985',
 '1971',
 '1977',
 '1973',
 '1956',
 '1983',
 '1987',
 '1955',
 '1980',
 '1983',
 '1949',
 '1984',
 '1945',
 '1983',
 '1998',
 '2003',
 '1987',
 '1950',
 '1964',
 '1967',
 '2004',
 '1991',
 '1998',
 '1971',
 '1983',
 '1983',
 '2001',
 '2018',
 '2016',
 '2013',
 '2011',
 '2011',
 '2011',
 '1967',
 '1984',
 '1928',
 '1965',
 '2009',
 '2008',
 '1986',
 '1940',
 '1984',
 '1969',
 '1945',
 '2010',
 '1955',
 '1984',
 '1965',
 '1952',
 '1971',
 '1984',
 '1982',
 '1971',
 '1984',
 '1980',
 '1986',
 '1986',
 '2010',
 '1897',
 '1906',
 '1984',
 '1968',
 '1980',
 '1950',
 '1967',
 '1955',
 '1984',
 '2007',
 '1984',
 '1974',
 '1948',
 '1921',
 '1955',
 '1988',
 '1969',
 '1981',
 '1894',
 '1967',
 '1966',
 '1965',
 '1964',
 '1955',
 '1965',
 '1965',
 '1937',
 '1974',
 '1975',
 '1945',
 '1940',
 '1961',
 '2008',
 '1976',
 '1977',
 '1962',
 '1962',
 '1931',
 '2008',
 '2008',
 '1916',
 '1983',
 '1968',
 '1984',
 '1983',
 '1976',
 '2004',
 '1972',
 '1972',
 '1936',
 '1925',
 '1964',
 '1980',
 '1982',
 '1928',
 '1935',
 '1933',
 '1986',
 '1983',
 '1969',
 '2005',
 '1962',
 '1937',
 '2007',
 '1972',
 '1982',
 '1962',
 '1966',
 '1941',
 '1968',
 '1896',
 '1983',
 '1910',
 '1974',
 '1967',
 '1982',
 '1965',
 '1982',
 '1924',
 '2008',
 '1977',
 '1944',
 '1971',
 '1966',
 '1967',
 '1964',
 '2022',
 '2014',
 '1919',
 '1969',
 '1970',
 '1970',
 '1972',
 '1951',
 '1970',
 '1972',
 '1908',
 '1974',
 '1984',
 '1967',
 '1967',
 '1969',
 '1996',
 '2001',
 '1969',
 '1996',
 '1974',
 '1970',
 '1969',
 '2001',
 '1985',
 '1981',
 '1986',
 '1963',
 '1947',
 '1947',
 '1959',
 '1960',
 '1963',
 '2006',
 '1959',
 '1959',
 '1967',
 '1937',
 '1999',
 '1946',
 '1997',
 '1972',
 '1967',
 '1922',
 '1968',
 '1942',
 '1959',
 '1980',
 '1967',
 '1995',
 '1948',
 '1990',
 '1995',
 '1984',
 '1971',
 '1994',
 '1983',
 '1995',
 '1971',
 '2004',
 '1972',
 '1976',
 '1983',
 '1983',
 '1930',
 '1978',
 '1982',
 '1976',
 '1991',
 '1983',
 '1962',
 '1973',
 '1965',
 '1961',
 '2009',
 ...]

In [24]:
school['설립연도'] = established_year

C:\Users\mgkan\AppData\Local\Temp/ipykernel_35432/2682051706.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  school['설립연도'] = established_year

In [25]:
school

,학교종류명,설립구분,표준학교코드,학교명,영문학교명,관할조직명,도로명우편번호,도로명주소,도로명상세주소,전화번호,...,설립일자,개교기념일,시도교육청코드,시도교육청명,소재지명,주야과정,계열명,학과명,적재일시,설립연도
1,초등학교,공립,7134150,서울숭신초등학교,Seoul Soongshin Elementary School,서울특별시성동광진교육지원청,4702,서울특별시 성동구 마장로 161,(하왕십리동),02-2252-5950,...,19590403,19590403,B10,서울특별시교육청,서울특별시,NaN,NaN,NaN,20230421,1959
2,중학교,공립,7134142,행당중학교,Haengdang Middle School,서울특별시성동광진교육지원청,4764,서울특별시 성동구 왕십리로 189,(행당동/행당중학교),02-2292-2721,...,19680806,19681002,B10,서울특별시교육청,서울특별시,NaN,NaN,NaN,20230421,1968
3,중학교,사립,7134141,한양대학교사범대학부속중학교,Hanyang University Middle School,서울특별시성동광진교육지원청,4761,서울특별시 성동구 마조로 42,(사근동/한양사대부속중?고등학교),02-2200-3700,...,19600118,19600118,B10,서울특별시교육청,서울특별시,NaN,NaN,NaN,20230421,1960
4,중학교,공립,7134140,자양중학교,Jayang Middle School,서울특별시성동광진교육지원청,5069,서울특별시 광진구 뚝섬로41길 33,(자양동/서울자양중학교),02-446-0365,...,19840301,19840301,B10,서울특별시교육청,서울특별시,NaN,NaN,NaN,20230421,1984
5,중학교,공립,7134139,용곡중학교,Yong-gok Middle School,서울특별시성동광진교육지원청,4940,서울특별시 광진구 용마산로22길 76,(중곡동/용곡중학교),02-452-2622,...,19821209,19830504,B10,서울특별시교육청,서울특별시,NaN,NaN,NaN,20230421,1982
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3891,고등학교,국립,1371663,국립전통예술고등학교,NATIONAL HIGH SCHOOL OF TRADITIONAL KOREAN ARTS,교육부,8650,서울특별시 금천구 시흥대로38길 62,(시흥동),02-896-1094,...,19600513,19600513,B10,서울특별시교육청,서울특별시,주간,예술계,창작연희과,20230421,1960
3892,고등학교,국립,1371663,국립전통예술고등학교,NATIONAL HIGH SCHOOL OF TRADITIONAL KOREAN ARTS,교육부,8650,서울특별시 금천구 시흥대로38길 62,(시흥동),02-896-1094,...,19600513,19600513,B10,서울특별시교육청,서울특별시,주간,예술계,타악과,20230421,1960
3893,고등학교,국립,1371663,국립전통예술고등학교,NATIONAL HIGH SCHOOL OF TRADITIONAL KOREAN ARTS,교육부,8650,서울특별시 금천구 시흥대로38길 62,(시흥동),02-896-1094,...,19600513,19600513,B10,서울특별시교육청,서울특별시,주간,예술계,한국음악과,20230421,1960
3895,고등학교,국립,1371661,국립국악고등학교,Gugak National High School,교육부,6311,서울특별시 강남구 개포로22길 65,(개포동/ 국악고등학교),02-3460-0500,...,19550401,19720909,B10,서울특별시교육청,서울특별시,주간,예술계,국악과,20230421,1955
3896,고등학교,국립,1371661,국립국악고등학교,Gugak National High School,교육부,6311,서울특별시 강남구 개포로22길 65,(개포동/ 국악고등학교),02-3460-0500,...,19550401,19720909,B10,서울특별시교육청,서울특별시,주간,예술계,무용과,20230421,1955

In [28]:
address = school['도로명주소']
address

1          서울특별시 성동구 마장로 161
2         서울특별시 성동구 왕십리로 189
3           서울특별시 성동구 마조로 42
4        서울특별시 광진구 뚝섬로41길 33
5       서울특별시 광진구 용마산로22길 76
                ...
3891    서울특별시 금천구 시흥대로38길 62
3892    서울특별시 금천구 시흥대로38길 62
3893    서울특별시 금천구 시흥대로38길 62
3895     서울특별시 강남구 개포로22길 65
3896     서울특별시 강남구 개포로22길 65
Name: 도로명주소, Length: 3502, dtype: object

In [30]:
#구글맵 api 로드
import googlemaps
from datetime import datetime

my_key = "AIzaSyBviCKefFJeOxVJyhO-wXMMuH512NSomwo" #구글맵 API 키값
maps = googlemaps.Client(key=my_key)

import time #구동 시간을 측정하기 위하여 time 모듈 임포트


lat = []  #위도
lng = []  #경도

i=0

t1 = time.time() #지오코딩 코드 처리 전 시각

for add in address:   
    i = i + 1
    try:
        geo_location = maps.geocode(add)[0].get('geometry')
        lat.append(geo_location['location']['lat'])
        lng.append(geo_location['location']['lng'])
        
# 좌표를 가져오지 못한 경우 에러 출력
    except:
        lat.append('')
        lng.append('')
        print("%d번 인덱스 에러"%(i))


print(time.time() - t1) #지오코딩 총 구동 시간

358.29963207244873

In [31]:
school['위도'] = lat
school['경도'] = lng

C:\Users\mgkan\AppData\Local\Temp/ipykernel_35432/1973264648.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  school['위도'] = lat
C:\Users\mgkan\AppData\Local\Temp/ipykernel_35432/1973264648.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  school['경도'] = lng

In [33]:
sum(school['위도'].isna())

0

In [35]:
school.to_csv('./Data/서울시학교좌표추가.csv', encoding='euc-kr')

In [41]:
data = pd.read_csv('./Data/서울시 대학 및 전문대학 DB 정보 (한국어).csv', encoding='euc-kr')
data.학교종류.unique()

array(['일반대학', '전문대학(3년제)', '전문대학(2년제)', '방송통신대학', '각종대학(대학)', '기능대학',
       '전공대학', '사이버대학(대학)', '산업대학', '교육대학'], dtype=object)

In [46]:
data[data['학교종류']=='사이버대학(대학)']

,키값,연도,학교종류,학교명,본분교,학교상태,설립,우편번호,주소,도로명주소,행정시,행정구,행정동,전화번호,팩스번호,홈페이지
46,BE_LiST23-0016,2013,사이버대학(대학),디지털서울문화예술대학교,본교,기존,사립,NaN,서울시 서대문구 통일로 37길 60 (홍제동 318-18),NaN,서울특별시,서대문구,홍제1동,02-2287-0222,02-379-8828,http://www.scau.ac.kr
51,BE_LiST23-0021,2013,사이버대학(대학),사이버한국외국어대학교,본교,기존,사립,NaN,서울 동대문구 이문동 한국외국어대학교,NaN,서울특별시,동대문구,이문1동,02-2173-2580,02-966-6183,http://www.cufs.ac.kr
62,BE_LiST23-0032,2013,사이버대학(대학),서울디지털대학교,본교,기존,사립,NaN,서울 마포구 도화동 560번지,NaN,서울특별시,마포구,도화동,02-1644-0982,02-2128-3006,http://www.sdu.ac.kr
63,BE_LiST23-0033,2013,사이버대학(대학),서울사이버대학교,본교,기존,사립,NaN,서울 강북구 솔매로49길 60(미아동 193-15) 서울사이버대학교,NaN,서울특별시,강북구,미아동,02-944-5000,02-980-2222,http://www.iscu.ac.kr

In [48]:
data['연도'].unique()

array([2013], dtype=int64)

In [47]:
address = data['주소']
address

0            서울 동대문구 서울시립대로 163 (전농동 90번지)
1                     서울 서대문구 홍제3동 서울여자간호대학
2                 서울특별시 노원구 화랑로 621 서울여자대학교
3           서울 중랑구 서일대학길 22(면목동 49-3) 서일대학교
4                          서울 구로구 항동 성공회대학교
                      ...
59                서울 서초구 서초중앙로 96(서초동 1650)
60                      서울 은평구 갈현로 4길 26-2호
61                       서울 관악구 관악로 1 서울대학교
62                         서울 마포구 도화동 560번지
63    서울 강북구 솔매로49길 60(미아동 193-15) 서울사이버대학교
Name: 주소, Length: 64, dtype: object

In [49]:
#구글맵 api 로드
import googlemaps
from datetime import datetime

my_key = "AIzaSyBviCKefFJeOxVJyhO-wXMMuH512NSomwo" #구글맵 API 키값
maps = googlemaps.Client(key=my_key)

import time #구동 시간을 측정하기 위하여 time 모듈 임포트


lat = []  #위도
lng = []  #경도

i=0

t1 = time.time() #지오코딩 코드 처리 전 시각

for add in address:   
    i = i + 1
    try:
        geo_location = maps.geocode(add)[0].get('geometry')
        lat.append(geo_location['location']['lat'])
        lng.append(geo_location['location']['lng'])
        
# 좌표를 가져오지 못한 경우 에러 출력
    except:
        lat.append('')
        lng.append('')
        print("%d번 인덱스 에러"%(i))


print(time.time() - t1) #지오코딩 총 구동 시간

9.339613199234009

In [50]:
data['위도'] = lat
data['경도'] = lng

In [52]:
data.to_csv('./Data/서울시대학교좌표추가.csv', encoding='euc-kr')