In [ ]:
import pandas as pd
import geopandas as gpd
from shapely.geometry import Point, Polygon, LineString
import matplotlib.pyplot as plt
import matplotlib
import matplotlib.font_manager as fm

In [ ]:
IC = pd.read_csv('./Data/1차정제/IC위치데이터.csv', encoding='euc-kr')

In [ ]:
IC

     Unnamed: 0    IC명    고속도로명         위도          경도
0             0   장수IC  서울외곽순환선  37.467329  126.754611
1             1  88JCT  인천국제공항선  37.577546  126.799884
2             2  산인JCT      남해선  35.272160  128.480154
3             3  서순천IC      남해선  35.000301  127.482820
4             4  도동JCT    대구포항선  35.913613  128.661718
..          ...    ...      ...        ...         ...
402         402  청원JCT    청주상주선  36.568911  127.431500
403         403   무안IC     서해안선  35.006912  126.491746
404         404   서천IC     서해안선  36.097115  126.688931
405         405   제천IC      중앙선  37.133821  128.143655
406         406   김포IC  서울외곽순환선  37.596893  126.775761

[407 rows x 5 columns]

In [ ]:
IC['경도'] = IC['경도'].astype(float)
IC['위도'] = IC['위도'].astype(float)
IC['geometry'] = IC.apply(lambda row : Point([row['경도'], row['위도']]), axis=1)
IC = gpd.GeoDataFrame(IC, geometry='geometry')
IC.crs = {'init':'epsg:4326'}
IC.to_file('./Data/1차정제/GEO/서울시IC위치.shp', encoding='euc-kr')

c:\Users\mgkan\anaconda3\lib\site-packages\pandas\core\dtypes\cast.py:118: ShapelyDeprecationWarning: The array interface is deprecated and will no longer work in Shapely 2.0. Convert the '.coords' to a numpy array instead.
  arr = construct_1d_object_array_from_listlike(values)
c:\Users\mgkan\anaconda3\lib\site-packages\pyproj\crs\crs.py:131: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  in_crs_string = _prepare_from_proj_string(in_crs_string)

In [ ]:
IC

,Unnamed: 0,IC명,고속도로명,위도,경도,geometry
0,0,장수IC,서울외곽순환선,37.467329,126.754611,POINT (126.75461 37.46733)
1,1,88JCT,인천국제공항선,37.577546,126.799884,POINT (126.79988 37.57755)
2,2,산인JCT,남해선,35.272160,128.480154,POINT (128.48015 35.27216)
3,3,서순천IC,남해선,35.000301,127.482820,POINT (127.48282 35.00030)
4,4,도동JCT,대구포항선,35.913613,128.661718,POINT (128.66172 35.91361)
...,...,...,...,...,...,...
402,402,청원JCT,청주상주선,36.568911,127.431500,POINT (127.43150 36.56891)
403,403,무안IC,서해안선,35.006912,126.491746,POINT (126.49175 35.00691)
404,404,서천IC,서해안선,36.097115,126.688931,POINT (126.68893 36.09712)
405,405,제천IC,중앙선,37.133821,128.143655,POINT (128.14365 37.13382)
406,406,김포IC,서울외곽순환선,37.596893,126.775761,POINT (126.77576 37.59689)

In [ ]:
bus = pd.read_csv('./Data/1차정제/서울시 버스정류소 위치정보.csv', encoding='euc-kr')

In [ ]:
bus

       정류소번호           정류소명         X좌표        Y좌표
0       1001        종로2가사거리  126.987750  37.569765
1       1002    창경궁.서울대학교병원  126.996566  37.579183
2       1003      명륜3가.성대입구  126.998340  37.582671
3       1004       종로2가.삼일교  126.987613  37.568579
4       1005  혜화동로터리.여운형활동터  127.001744  37.586243
...      ...            ...         ...        ...
12554  25995          우성아파트  127.139339  37.550386
12555  25996          우성아파트  127.140046  37.550643
12556  25997           조일약국  127.123596  37.533630
12557  25998           성내시장  127.125497  37.536155
12558  25999    천호우체국.로데오거리  127.127337  37.540343

[12559 rows x 4 columns]

In [ ]:
bus['X좌표'] = bus['X좌표'].astype(float)
bus['Y좌표'] = bus['Y좌표'].astype(float)
bus['geometry'] = bus.apply(lambda row : Point([row['X좌표'], row['Y좌표']]), axis=1)
bus = gpd.GeoDataFrame(bus, geometry='geometry')
bus.crs = {'init':'epsg:4326'}
bus.to_file('./Data/1차정제/GEO/서울시버스정류장위치.shp', encoding='euc-kr')

c:\Users\mgkan\anaconda3\lib\site-packages\pandas\core\dtypes\cast.py:118: ShapelyDeprecationWarning: The array interface is deprecated and will no longer work in Shapely 2.0. Convert the '.coords' to a numpy array instead.
  arr = construct_1d_object_array_from_listlike(values)
c:\Users\mgkan\anaconda3\lib\site-packages\pyproj\crs\crs.py:131: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method. When making the change, be mindful of axis order changes: https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6
  in_crs_string = _prepare_from_proj_string(in_crs_string)

In [ ]:
bus

       정류소번호           정류소명         X좌표        Y좌표                    geometry
0       1001        종로2가사거리  126.987750  37.569765  POINT (126.98775 37.56977)
1       1002    창경궁.서울대학교병원  126.996566  37.579183  POINT (126.99657 37.57918)
2       1003      명륜3가.성대입구  126.998340  37.582671  POINT (126.99834 37.58267)
3       1004       종로2가.삼일교  126.987613  37.568579  POINT (126.98761 37.56858)
4       1005  혜화동로터리.여운형활동터  127.001744  37.586243  POINT (127.00174 37.58624)
...      ...            ...         ...        ...                         ...
12554  25995          우성아파트  127.139339  37.550386  POINT (127.13934 37.55039)
12555  25996          우성아파트  127.140046  37.550643  POINT (127.14005 37.55064)
12556  25997           조일약국  127.123596  37.533630  POINT (127.12360 37.53363)
12557  25998           성내시장  127.125497  37.536155  POINT (127.12550 37.53615)
12558  25999    천호우체국.로데오거리  127.127337  37.540343  POINT (127.12734 37.54034)

[12559 rows x 5 columns]